# Generated by Django 4.1 on 2024-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormApp", "0002_modelsetpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.BigIntegerField()),
                ("picture", models.FileField(upload_to="picture")),
            ],
        ),
    ]
