# Generated by Django 4.1 on 2024-04-15 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApp", "0002_makeDB"),
    ]

    operations = [
        migrations.CreateModel(
            name="Girl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("birthday", models.DateField(default="2000-03-01")),
            ],
        ),
        migrations.AlterField(
            model_name="person",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 15, 9, 55, 22, 96092, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="update_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 15, 9, 55, 22, 96250, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Boy",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("birthday", models.DateField(default="2000-01-01")),
                (
                    "girlfriend",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ModelApp.girl",
                    ),
                ),
            ],
        ),
    ]
